export function FakeItems() {
    const categories = [
        {id: 1, name:"T-shirt"},
        {id: 2, name:"Chaussures"},
    ]

    const brands = [
        {id: 1, name:"Nike"},
        {id: 2, name:"Adidas"},
        {id: 3, name:"Puma"},
        {id: 4, name:"Reebok"},
        {id: 5, name:"Under Armour"},
        {id: 6, name:"New Balance"},
        {id: 7, name:"Asics"},
        {id: 8, name:"Converse"},
        {id: 9, name:"Vans"},
        {id: 10, name:"Skechers"},
        {id: 11, name:"Fila"},
        {id: 12, name:"Kappa"},
        {id: 13, name:"Lacoste"},
        {id: 14, name:"Le Coq Sportif"},
        {id: 15, name:"Diadora"},
        {id: 16, name:"K-Swiss"},
        {id: 17, name:"Onitsuka Tiger"},
        {id: 18, name:"Hoka One One"},
        {id: 19, name:"Salomon"},
        {id: 20, name:"Mey"},
    ]

    const items = [
        { id: 1, name: "T-shirt 1", brand: brands[0], category: categories[0] ,price: 19.99, image: "/img/tshirt/ts1.png", description: "Voici la description factice d'un article factice pour les éléments factice du projet factice. Piwee!" },
        { id: 2, name: "T-shirt 2", brand: brands[18], category: categories[0] ,price: 24.99, image: "/img/tshirt/ts2.png", description: "Voici la description factice d'un article factice pour les éléments factice du projet factice. Piwee!" },
        { id: 3, name: "T-shirt 3", brand: brands[18], category: categories[0] ,price: 29.99, image: "/img/tshirt/ts3.png", description: "Voici la description factice d'un article factice pour les éléments factice du projet factice. Piwee!" },
        { id: 4, name: "T-shirt 4", brand: brands[18], category: categories[0] ,price: 34.99, image: "/img/tshirt/ts4.png", description: "Voici la description factice d'un article factice pour les éléments factice du projet factice. Piwee!" },
        { id: 5, name: "T-shirt 5", brand: brands[19], category: categories[0] ,price: 39.99, image: "/img/tshirt/ts5.png", description: "Voici la description factice d'un article factice pour les éléments factice du projet factice. Piwee!" },
        { id: 6, name: "T-shirt 6", brand: brands[18], category: categories[0] ,price: 44.99, image: "/img/tshirt/ts6.png", description: "Voici la description factice d'un article factice pour les éléments factice du projet factice. Piwee!" },
        { id: 7, name: "T-shirt 7", brand: brands[18], category: categories[0] ,price: 49.99, image: "/img/tshirt/ts7.png", description: "Voici la description factice d'un article factice pour les éléments factice du projet factice. Piwee!" },
        { id: 8, name: "T-shirt 8",brand: brands[19],  category: categories[0] ,price: 54.99, image: "/img/tshirt/ts8.png", description: "Voici la description factice d'un article factice pour les éléments factice du projet factice. Piwee!" },
        { id: 9, name: "Chaussures 1", brand: brands[0], category: categories[1] ,price: 59.99, image: "/img/shoes/shoes1.png", description: "Voici la description factice d'un article factice pour les éléments factice du projet factice. Piwee!" },
        { id: 10, name: "Chaussures 2", brand: brands[0], category: categories[1] ,price: 64.99, image: "/img/shoes/shoes2.png", description: "Voici la description factice d'un article factice pour les éléments factice du projet factice. Piwee!" },
        { id: 11, name: "Chaussures 3", brand: brands[0], category: categories[1] ,price: 69.99, image: "/img/shoes/shoes3.png", description: "Voici la description factice d'un article factice pour les éléments factice du projet factice. Piwee!" },
        { id: 12, name: "Chaussures 4", brand: brands[4], category: categories[1] ,price: 74.99, image: "/img/shoes/shoes4.png", description: "Voici la description factice d'un article factice pour les éléments factice du projet factice. Piwee!" },
        { id: 13, name: "Chaussures 5", brand: brands[0], category: categories[1] ,price: 79.99, image: "/img/shoes/shoes5.png", description: "Voici la description factice d'un article factice pour les éléments factice du projet factice. Piwee!" },
        { id: 14, name: "Chaussures 6", brand: brands[2], category: categories[1] ,price: 84.99, image: "/img/shoes/shoes6.png", description: "Voici la description factice d'un article factice pour les éléments factice du projet factice. Piwee!" },
        { id: 15, name: "Chaussures 7", brand: brands[0], category: categories[1] ,price: 89.99, image: "/img/shoes/shoes7.png", description: "Voici la description factice d'un article factice pour les éléments factice du projet factice. Piwee!" },
        { id: 16, name: "Chaussures 8", brand: brands[20], category: categories[1] ,price: 94.99, image: "/img/shoes/shoes8.png", description: "Voici la description factice d'un article factice pour les éléments factice du projet factice. Piwee!" },
        { id: 17, name: "Chaussures 9", brand: brands[0], category: categories[1] ,price: 99.99, image: "/img/shoes/shoes9.png", description: "Voici la description factice d'un article factice pour les éléments factice du projet factice. Piwee!" },
        { id: 18, name: "Chaussures 10", brand: brands[0], category: categories[1] ,price: 104.99, image: "/img/shoes/shoes10.png", description: "Voici la description factice d'un article factice pour les éléments factice du projet factice. Piwee!" },
        { id: 19, name: "Chaussures 11", brand: brands[0], category: categories[1] ,price: 109.99, image: "/img/shoes/shoes11.png", description: "Voici la description factice d'un article factice pour les éléments factice du projet factice. Piwee!" },
        { id: 20, name: "Chaussures 12", brand: brands[0], category: categories[1] ,price: 114.99, image: "/img/shoes/shoes12.png", description: "Voici la description factice d'un article factice pour les éléments factice du projet factice. Piwee!" },
        { id: 21, name: "Chaussures 13", brand: brands[0], category: categories[1] ,price: 119.99, image: "/img/shoes/shoes13.png", description: "Voici la description factice d'un article factice pour les éléments factice du projet factice. Piwee!" },
        { id: 22, name: "Chaussures 14", brand: brands[0], category: categories[1] ,price: 124.99, image: "/img/shoes/shoes14.png", description: "Voici la description factice d'un article factice pour les éléments factice du projet factice. Piwee!" },
        { id: 23, name: "Chaussures 15", brand: brands[0], category: categories[1] ,price: 129.99, image: "/img/shoes/shoes15.png", description: "Voici la description factice d'un article factice pour les éléments factice du projet factice. Piwee!" },
        { id: 24, name: "Chaussures 16", brand: brands[0], category: categories[1] ,price: 134.99, image: "/img/shoes/shoes16.png", description: "Voici la description factice d'un article factice pour les éléments factice du projet factice. Piwee!" },
        { id: 25, name: "Chaussures 17", brand: brands[0], category: categories[1] ,price: 139.99, image: "/img/shoes/shoes17.png", description: "Voici la description factice d'un article factice pour les éléments factice du projet factice. Piwee!" },
        { id: 26, name: "Chaussures 18", brand: brands[0], category: categories[1] ,price: 144.99, image: "/img/shoes/shoes18.png", description: "Voici la description factice d'un article factice pour les éléments factice du projet factice. Piwee!" },
        { id: 27, name: "Chaussures 19", brand: brands[0], category: categories[1] ,price: 149.99, image: "/img/shoes/shoes19.png", description: "Voici la description factice d'un article factice pour les éléments factice du projet factice. Piwee!" }, 
        { id: 28, name: "Chaussures 20", brand: brands[0], category: categories[1] ,price: 154.99, image: "/img/shoes/shoes20.png", description: "Voici la description factice d'un article factice pour les éléments factice du projet factice. Piwee!" },
        { id: 29, name: "Chaussures 21", brand: brands[0], category: categories[1] ,price: 159.99, image: "/img/shoes/shoes21.png", description: "Voici la description factice d'un article factice pour les éléments factice du projet factice. Piwee!" },
        { id: 30, name: "Chaussures 22", brand: brands[0], category: categories[1] ,price: 164.99, image: "/img/shoes/shoes22.png", description: "Voici la description factice d'un article factice pour les éléments factice du projet factice. Piwee!" },
        { id: 31, name: "Chaussures 23", brand: brands[0], category: categories[1] ,price: 169.99, image: "/img/shoes/shoes23.png", description: "Voici la description factice d'un article factice pour les éléments factice du projet factice. Piwee!" },  
        { id: 32, name: "Chaussures 24", brand: brands[0], category: categories[1] ,price: 174.99, image: "/img/shoes/shoes24.png", description: "Voici la description factice d'un article factice pour les éléments factice du projet factice. Piwee!" },
        { id: 33, name: "Chaussures 25", brand: brands[0], category: categories[1] ,price: 179.99, image: "/img/shoes/shoes25.png", description: "Voici la description factice d'un article factice pour les éléments factice du projet factice. Piwee!" },
        { id: 34, name: "Chaussures 26", brand: brands[0], category: categories[1] ,price: 184.99, image: "/img/shoes/shoes26.png", description: "Voici la description factice d'un article factice pour les éléments factice du projet factice. Piwee!" },
        { id: 35, name: "Chaussures 27", brand: brands[0], category: categories[1] ,price: 189.99, image: "/img/shoes/shoes27.png", description: "Voici la description factice d'un article factice pour les éléments factice du projet factice. Piwee!" },
        { id: 36, name: "Chaussures 28", brand: brands[0], category: categories[1] ,price: 194.99, image: "/img/shoes/shoes28.png", description: "Voici la description factice d'un article factice pour les éléments factice du projet factice. Piwee!" },
    ];

    return { categories, items , brands};   
}