export function FakeItems() {
    const categories = [
        {id: 1, name:"T-shirt"},
        {id: 2, name:"Chaussures"},
    ]

    const brands = [
        {id: 1, name:"Nike"},
        {id: 2, name:"Adidas"},
        {id: 3, name:"Puma"},
        {id: 4, name:"Reebok"},
        {id: 5, name:"Under Armour"},
        {id: 6, name:"New Balance"},
        {id: 7, name:"Asics"},
        {id: 8, name:"Converse"},
        {id: 9, name:"Vans"},
        {id: 10, name:"Skechers"},
        {id: 11, name:"Fila"},
        {id: 12, name:"Kappa"},
        {id: 13, name:"Lacoste"},
        {id: 14, name:"Le Coq Sportif"},
        {id: 15, name:"Diadora"},
        {id: 16, name:"K-Swiss"},
        {id: 17, name:"Onitsuka Tiger"},
        {id: 18, name:"Hoka One One"},
        {id: 19, name:"Salomon"},
        {id: 20, name:"Mey"},
    ]

    const items = [
        { id: 1, name: "StreetTone Classic", brand: brands[0], category: categories[0], price: 19.99, image: "/img/tshirt/ts1.png", description: "Un t-shirt au style urbain intemporel, parfait pour afficher une allure décontractée avec une touche de caractère." },
        { id: 2, name: "Drip Motion Tee", brand: brands[18], category: categories[0], price: 24.99, image: "/img/tshirt/ts2.png", description: "Exprime ton flow avec ce t-shirt fluide et stylé, conçu pour bouger avec toi, du matin au soir." },
        { id: 3, name: "Pulse Fade", brand: brands[18], category: categories[0], price: 29.99, image: "/img/tshirt/ts3.png", description: "Un dégradé moderne qui capte l'énergie de la rue. Parfait pour ceux qui vivent au rythme du bitume." },
        { id: 4, name: "CoreLayer Fit", brand: brands[18], category: categories[0], price: 34.99, image: "/img/tshirt/ts4.png", description: "Confort et structure réunis dans ce tee minimaliste conçu comme base de ton style quotidien." },
        { id: 5, name: "UrbanFrame Tee", brand: brands[19], category: categories[0], price: 39.99, image: "/img/tshirt/ts5.png", description: "Encadre ton look avec ce t-shirt à coupe nette, pensé pour la jungle urbaine et les esprits affûtés." },
        { id: 6, name: "Neon Thread", brand: brands[18], category: categories[0], price: 44.99, image: "/img/tshirt/ts6.png", description: "Un éclat subtil et une couture impeccable : ce t-shirt illumine ton outfit sans en faire trop." },
        { id: 7, name: "Gravity Stitch", brand: brands[18], category: categories[0], price: 49.99, image: "/img/tshirt/ts7.png", description: "Un t-shirt qui garde les pieds sur terre avec un design équilibré et une couture de qualité supérieure." },
        { id: 8, name: "EchoWear Basic", brand: brands[19], category: categories[0], price: 54.99, image: "/img/tshirt/ts8.png", description: "Le basique qui fait écho à ton style : simple, efficace, et taillé pour durer." },
        { id: 9, name: "Nova Drift V1", brand: brands[0], category: categories[1], price: 59.99, image: "/img/shoes/shoes1.png", description: "Un design galactique aux lignes aérodynamiques. Pour ceux qui filent vers l'infini, version 1.0." },
        { id: 10, name: "Shadow Pulse 92", brand: brands[0], category: categories[1], price: 64.99, image: "/img/shoes/shoes2.png", description: "Inspirées des 90s avec une touche techno. Marche dans l’ombre avec assurance." },
        { id: 11, name: "BlazeCore X", brand: brands[0], category: categories[1], price: 69.99, image: "/img/shoes/shoes3.png", description: "Une explosion de style et de performance. Ces sneakers sont faites pour aller droit au cœur de l'action." },
        { id: 12, name: "Urban Echo LX", brand: brands[4], category: categories[1], price: 74.99, image: "/img/shoes/shoes4.png", description: "Conçues pour résonner dans les rues, les Urban Echo LX allient élégance et rythme urbain." },
        { id: 13, name: "Frostbite 7", brand: brands[0], category: categories[1], price: 79.99, image: "/img/shoes/shoes5.png", description: "Fraîcheur extrême et style glacial. La Frostbite 7 ne craint aucun terrain." },
        { id: 14, name: "Skyline Flow", brand: brands[2], category: categories[1], price: 84.99, image: "/img/shoes/shoes6.png", description: "Une silhouette aérienne pour ceux qui avancent avec légèreté et confiance dans la ville." },
        { id: 15, name: "Nebula Rise", brand: brands[0], category: categories[1], price: 89.99, image: "/img/shoes/shoes7.png", description: "Un pas dans la galaxie. Laisse-toi propulser par ce modèle aussi audacieux qu’élégant." },
        { id: 16, name: "Voltage Runner", brand: brands[20], category: categories[1], price: 94.99, image: "/img/shoes/shoes8.png", description: "Remplies d’énergie et prêtes à bondir, ces sneakers électrisent ta foulée." },
        { id: 17, name: "IronStep Prime", brand: brands[0], category: categories[1], price: 99.99, image: "/img/shoes/shoes9.png", description: "Solidité, style, précision. Pour les leaders qui ne font jamais un pas en arrière." },
        { id: 18, name: "Crimson Orbit", brand: brands[0], category: categories[1], price: 104.99, image: "/img/shoes/shoes10.png", description: "Une fusion entre feu et vitesse. Tourne en orbite autour du style avec audace." },
        { id: 19, name: "Gravity Flex", brand: brands[0], category: categories[1], price: 109.99, image: "/img/shoes/shoes11.png", description: "Confort gravitationnel garanti. Pour ceux qui veulent de la souplesse sans perdre l’ancrage." },
        { id: 20, name: "Phantom Arc", brand: brands[0], category: categories[1], price: 114.99, image: "/img/shoes/shoes12.png", description: "Silencieuses mais percutantes. Les Phantom Arc sont faites pour se démarquer sans un bruit." },
        { id: 21, name: "Spectra Drift", brand: brands[0], category: categories[1], price: 119.99, image: "/img/shoes/shoes13.png", description: "Un mélange de couleurs et de mouvement pour ceux qui surfent sur les tendances avec grâce." },
        { id: 22, name: "Lunar Fade X", brand: brands[0], category: categories[1], price: 124.99, image: "/img/shoes/shoes14.png", description: "Des reflets lunaires et un dégradé futuriste pour une allure venue d'ailleurs." },
        { id: 23, name: "Midnight Surge", brand: brands[0], category: categories[1], price: 129.99, image: "/img/shoes/shoes15.png", description: "Puissance nocturne incarnée. Idéales pour les explorateurs de la nuit urbaine." },
        { id: 24, name: "Astro Dash Pro", brand: brands[0], category: categories[1], price: 134.99, image: "/img/shoes/shoes16.png", description: "Des sneakers qui accélèrent le pas comme une étoile filante. Fonce vers ton style." },
        { id: 25, name: "Inferno Glide", brand: brands[0], category: categories[1], price: 139.99, image: "/img/shoes/shoes17.png", description: "Un look enflammé et une glisse parfaite pour affronter la rue avec audace." },
        { id: 26, name: "Horizon Fade", brand: brands[0], category: categories[1], price: 144.99, image: "/img/shoes/shoes18.png", description: "Le style au lever du jour. Une teinte qui s’étend à l’infini, comme ta vision." },
        { id: 27, name: "Stealth Nomad", brand: brands[0], category: categories[1], price: 149.99, image: "/img/shoes/shoes19.png", description: "Discrètes, mobiles, et prêtes pour toutes les aventures urbaines. Pour les esprits libres." },
        { id: 28, name: "Ignite Nova", brand: brands[0], category: categories[1], price: 154.99, image: "/img/shoes/shoes20.png", description: "Chaque pas déclenche une étincelle. Les Ignite Nova brillent par leur audace." },
        { id: 29, name: "CyberRush 3K", brand: brands[0], category: categories[1], price: 159.99, image: "/img/shoes/shoes21.png", description: "Une technologie de course cybernétique pour foncer dans le futur avec style." },
        { id: 30, name: "EchoStride S2", brand: brands[0], category: categories[1], price: 164.99, image: "/img/shoes/shoes22.png", description: "Chaque foulée laisse un écho. Pour les coureurs qui laissent une empreinte." },
        { id: 31, name: "Nimbus Core", brand: brands[0], category: categories[1], price: 169.99, image: "/img/shoes/shoes23.png", description: "Légèreté céleste et confort ultime. Pour flotter au-dessus du bitume." },
        { id: 32, name: "Rebel Edge V2", brand: brands[0], category: categories[1], price: 174.99, image: "/img/shoes/shoes24.png", description: "Deuxième génération, même esprit rebelle. Pour ceux qui n’acceptent pas les règles du style." },
        { id: 33, name: "Spectra Glide Z", brand: brands[0], category: categories[1], price: 179.99, image: "/img/shoes/shoes25.png", description: "Une glisse chromatique dans les rues, avec une touche de luxe et de mouvement." },
        { id: 34, name: "Volt Mirage", brand: brands[0], category: categories[1], price: 184.99, image: "/img/shoes/shoes26.png", description: "Un éclair de vitesse et un mirage de style. Pour courir entre deux mondes." },
        { id: 35, name: "Zenith Pulse", brand: brands[0], category: categories[1], price: 189.99, image: "/img/shoes/shoes27.png", description: "Le sommet du style et du rythme. Marche au cœur de la vibration urbaine." },
        { id: 36, name: "Obsidian Drift", brand: brands[0], category: categories[1], price: 194.99, image: "/img/shoes/shoes28.png", description: "Profondeur et élégance en mouvement. L’obsidienne au service de la street culture." }
    ];
    return { categories, items , brands};   
}